### ISSUE TITLE
not working for this script

### ISSUE THREAD

**Issue by erichuang2015** [haccer/available#1]
hello

I try this script and run , no thing to print , and I debug and print someting like

                fmt.Println( available.Domain(domain))
it return false in go console

**Comment by haccer** [comment]
The `Domain` function returns true or false:
```Go
func Domain(domain string) (available bool)
```

**Comment by erichuang2015** [comment]
hello

What i mean is that whatever the domain is available  or not , it always went to false, the code I debug is as below 

func main() {
        domain := "dreamdossssmain.io"

        available := available.Domain(domain)

        fmt.Println(available)
}

**Comment by haccer** [comment]
That's strange, the code with a domain that doesn't exist appears as true:

```
➜  ~ cat test.go
package main

import (
	"fmt"
	"github.com/haccer/available"
)

func main() {
	domain := "dreamdossssmain.io"

	available := available.Domain(domain)

	fmt.Println(available)
}
➜  ~ go run test.go
true
➜  ~
```

Here's with an existing domain:
```
➜  ~ cat test.go
package main

import (
	"fmt"
	"github.com/haccer/available"
)

func main() {
	domain := "real.io"

	available := available.Domain(domain)

	fmt.Println(available)
}
➜  ~ go run test.go
false
➜  ~
```
